username: "wiktortheboss"
client_id: "5a50ec388e014dda8c475275e7a39631"
client_secret: "58ce595bfef64775aea3a7a32bd83116"
playlist_id: "7CmhspYGeOG8yR9cQqhKL5"
redirect_uri: "http://localhost:8888/callback"